### PR TITLE
Brute force auth

### LINKED ISSUE #73: [Vulnerability] Prevent brute force auth attempts
https://www.baeldung.com/spring-security-block-brute-force-authentication-attempts
Critical: [CWE-930] Improper Restriction of Excessive Authentication Attempts

Limit the number of consecutive failed authentication attempts to 3. 

If an IP address performs 3 consecutive failed authentication attempts, block it for a given amount of time (e.g., 20 mins).

### PR DESCRIPTION
**Pull request by rajitbanerjee**
Closes #73 

- Block IP for 20 mins after 3 failed auths.
- Update password strengths for pre-populated users in database (changed default from `password` to `Admin!234`) to maintain new password standards.
- Update node version in dockerfile.

image

### CODE REVIEW

File: backend/src/main/java/com/vax/warden/security/LoginAttemptService.java [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+        } catch (ExecutionException e) {
+            attempts = 0;
+        }
+        attempts++;
+        attemptsCache.put(key, attempts);
+    }
+
+    public boolean isBlocked(String key) {
+        try {
+            return attemptsCache.get(key) >= MAX_ATTEMPTS;
```
Comment (AmplifiedHuman) [inline backend/src/main/java/com/vax/warden/security/LoginAttemptService.java:55]: should this be `>` instead of `>=` since it's maximum allowed attempts I presume?

File: backend/src/main/java/com/vax/warden/security/LoginAttemptService.java [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+                                    public Integer load(String key) {
+                                        return 0;
+                                    }
+                                });
+    }
+
+    public static String getClientIP(HttpServletRequest request) {
+        final String xfHeader = request.getHeader("X-Forwarded-For");
+        if (xfHeader != null) {
+            return xfHeader.split(",")[0];
```
Comment (AmplifiedHuman) [inline backend/src/main/java/com/vax/warden/security/LoginAttemptService.java:33]: might be cause exceptions, consider the case `"".split(",")` which results in `[]`.

**Review by AmplifiedHuman — CHANGES_REQUESTED** [review]
minor review needed

File: backend/src/main/java/com/vax/warden/security/LoginAttemptService.java (hunk 1 above)
Comment (rajitbanerjee) [reply backend/src/main/java/com/vax/warden/security/LoginAttemptService.java:55]: It works with `>=` since once `MAX_ATTEMPTS` is reached, the IP should be blocked. E.g. 
- failed attempts = 1: don't block next attempt
- failed attempts = 2: don't block next attempt
- failed attempts = 3: BLOCK *next* attempt
Hence the 4th attempt is blocked, despite being potentially successful.

"If an IP address performs 3 consecutive failed authentication attempts, block it for a given amount of time (e.g., 20 mins)."

Comment (AmplifiedHuman) [reply backend/src/main/java/com/vax/warden/security/LoginAttemptService.java:55]: alright thanks for clarifying, this makes sense

File: backend/src/main/java/com/vax/warden/security/LoginAttemptService.java (hunk 2 above)
Comment (rajitbanerjee) [reply backend/src/main/java/com/vax/warden/security/LoginAttemptService.java:35]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For#syntax
`X-Forwarded-For: <client>, <proxy1>, <proxy2>`
I believe if the xff header exists (usually doesn't), it follows the syntax shown above (so a command separated list)

Comment (AmplifiedHuman) [reply backend/src/main/java/com/vax/warden/security/LoginAttemptService.java:35]: yup this looks good

**Review by AmplifiedHuman — APPROVED** [review]
approved, issues clarified.
